---
title: "Project"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)


CA <- read.csv("CA.csv")

head(CA,10)

dim(CA)
colnames(CA)

unique(CA$County)

b <- "Solano"
a <- CA %>% filter(County == b)
a
CA.pop <- read.csv("california_county_population.csv")
CA.pop

head(CA)
```


```{r}

a1 <- CA %>% group_by(TMC) %>% summarise(count = n())
a1

plot <- ggplot(data = a1) + geom_bar(aes(x = reorder(TMC, -count),y = count), stat = "identity") # + theme(axis.text.x = element_text(angle = 90))

plot

```


```{r}
a2 <- CA %>% group_by(Severity) %>% summarise(count = n())
a2

plot1 <- ggplot(data = CA) + geom_bar(aes(x = Severity, y = ..count..)) 
plot1

plot2 <- ggplot(data = a2) + geom_bar(aes(x = "", y = count, fill=Severity), stat = "identity") + coord_polar("y", start=0)
plot2

```


```{r}
head(CA,15)
a <- substr( CA[1,"Start_Time"] ,12,19)
a
format(strptime(a,"%H:%M:%S"),'%H')

a3 <- CA %>% mutate(hour = format(strptime(substr(Start_Time,12,19),"%H:%M:%S"),'%H'))
a3

plot <- ggplot(data = a3) + geom_bar(aes(x = hour ,y = ..count..)) # + theme(axis.text.x = element_text(angle = 90))
plot

```


```{r}
head(CA)

a4 <- CA %>% group_by(day, ph) %>% summarise(count = n())
a4

plot <- ggplot(data = a4) + geom_bar(aes(x = day ,y = count, fill = ph), stat="identity") # + theme(axis.text.x = element_text(angle = 90))
plot

```


```{r}

head(CA$date,15)

a5 <- CA %>% mutate(month = substr(date,6,7))
a5 <- a5 %>% group_by(month, Severity) %>% summarise(count = n())
a5


plot <- ggplot(data = a5) + geom_bar(aes(x = month ,y = count, fill = Severity ), stat = "identity") # + theme(axis.text.x = element_text(angle = 90))
plot

```


```{r}
plot <- ggplot(data = CA) + geom_bar(aes(x = Bump ,y = ..count..)) # + theme(axis.text.x = element_text(angle = 90))
plot

```


```{r}

plot <- ggplot(data = CA) + geom_bar(aes(x = Stop ,y = ..count..)) # + theme(axis.text.x = element_text(angle = 90))
plot

```


```{r}
plot <- ggplot(data = CA) + geom_bar(aes(x = Give_Way ,y = ..count..)) # + theme(axis.text.x = element_text(angle = 90))
plot

```


```{r}
plot <- ggplot(data = CA) + geom_bar(aes(x = No_Exit ,y = ..count..)) # + theme(axis.text.x = element_text(angle = 90))
plot

```


```{r}
plot <- ggplot(data = CA) + geom_bar(aes(x = Traffic_Signal ,y = ..count..)) # + theme(axis.text.x = element_text(angle = 90))
plot

```


```{r}

a6 <- CA %>% group_by(Visibility.mi.) %>% summarise(count =n())
a6

plot <- ggplot(data = a6) + geom_density(aes(x = Visibility.mi. ,y = count), stat="identity") +scale_x_continuous(limits = c(0,15))
plot
```



```{r}

library(leaflet)
library(dplyr)
library(htmlwidgets)

df <- read.csv("CA.csv")
sam.df <- sample_n(df, 6000)

severity.list <- c(1, 2, 3, 4)
factPal <- colorFactor(c("green", "yellow", "orange", "red"), severity.list, ordered = T)

m <- leaflet() %>%  addTiles()

for (i in 1:4) {
  severity.level <- sam.df[sam.df$Severity == severity.list[i],]
  
  m <- addCircleMarkers(m,
                        data = severity.level,
                        lng = ~Start_Lng,
                        lat = ~Start_Lat, 
                        popup = ~Street,
                        radius = 0.5,
                        fillOpacity = 1,
                        color = factPal(severity.level$Severity),
                        group = severity.list[i])
}

m <- addLayersControl(m, overlayGroups = severity.list)
m

saveWidget(m, "heatmap.html")




```


```{r}

library(dplyr)
library(ggplot2)


CA <- read.csv("CA.csv")


cal.pop <- read.csv("california_county_population.csv")
cal.pop
colnames(cal.pop)
cal <- cal.pop %>% group_by(CTYNAME) %>% summarise(pop = sum(TOT_POP))
cal
a<- as.numeric( cal[cal$CTYNAME == "Solano","pop"])
str(a)

cal.county.pop <- read.csv("california_county_population.csv")
county.pop <- cal.county.pop %>% group_by(CTYNAME) %>% summarise(pop = sum(TOT_POP))
county.pop

county.veh <- read.csv("estimated vehicles by county.csv")
county.veh <- county.veh[-59,]
county.veh$COUNTIES <- county.pop$CTYNAME
county.veh <- as.data.frame(lapply(county.veh, function(y) gsub(",", "", y))) 
county.veh$TOTAL <- as.numeric(as.character(county.veh$TOTAL))
county.veh
```




```{r}

CA <- read.csv("CA.csv")

data1 <- CA %>% group_by(County) %>% summarise(count=n())

cal.county.pop <- read.csv("california_county_population.csv")
county.pop <- cal.county.pop %>% group_by(CTYNAME) %>% summarise(pop = sum(TOT_POP))
data1 <- left_join(data1,county.pop, by=c("County"="CTYNAME"))
data1 <- data1 %>% mutate(pop.rate = count*1000/pop)
#data1 <- data1[order(data1$pop.rate, decreasing = T),]

county.veh <- read.csv("estimated vehicles by county.csv")
county.veh <- county.veh[-59,]
county.veh$COUNTIES <- county.pop$CTYNAME
county.veh <- as.data.frame(lapply(county.veh, function(y) gsub(",", "", y))) 
county.veh$TOTAL <- as.numeric(as.character(county.veh$TOTAL))

data1 <- left_join(data1,county.veh[,c("COUNTIES","TOTAL")], by=c("County"="COUNTIES"))
data1 <- data1 %>% mutate(veh.rate = count*1000/TOTAL)
colnames(data1) <- c("County", "no.accidents", "total.pop", "pop.rate", "total.veh", "veh.rate")


ggplot(data=data1) +
  geom_bar(aes(x=reorder(County,-pop.rate), y=no.accidents), fill="black", alpha=0.5, stat="identity") +
  geom_line(aes(x=reorder(County,-pop.rate), y= pop.rate*5000), group=1,  color="red", stat="identity") +
  geom_line(aes(x=reorder(County,-pop.rate), y= veh.rate*5000), group=1,  color="blue", stat="identity") +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + 
  theme(axis.text.x=element_text(angle=90)) 
  

ggplot(data=data1) +
  geom_line(aes(x=reorder(County,-pop), y= pop), group=1,  fill="blue", stat="identity") +
  theme(axis.text.x=element_text(angle=90))
```



```{r}

library(tidyr)

summary(CA)
head(CA)

gsub(CA$Bump, "False", 0)

data2 <- CA %>% group_by(County) %>% summarise() 

spread(data2, Bump, count)


ggplot(CA) + geom_bar(aes(x = Bump))

```



























